using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Apprefine.MattermostBots.Common.Models
{
    public class MattermostOptions
    {
        public string ApiUrl { get; set; }

        /// <summary>
        /// Personal Access Token generated by an admin
        /// </summary>
        public string Token { get; set; }

        /// <summary>
        /// Token given to you when creating slash commands.
        /// These are used to verify that the request came from your team.
        /// If this is not empty and the token in request is not valid
        /// then the request will be rejected.
        /// </summary>
        public List<string> VerificationTokens { get; set; }
    }
}
