// <auto-generated />
using Apprefine.MattermostBots.PollBot.Consts;
using Apprefine.MattermostBots.PollBot.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Apprefine.MattermostBots.PollBot.Migrations
{
    [DbContext(typeof(PollBotContext))]
    [Migration("20180218185712_MoreColumns")]
    partial class MoreColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Apprefine.MattermostBots.PollBot.Entities.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AvailableAnswers")
                        .HasMaxLength(4000);

                    b.Property<string>("ChannelId");

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<string>("OwnerId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("Apprefine.MattermostBots.PollBot.Entities.PollAnswer", b =>
                {
                    b.Property<int>("PollId");

                    b.Property<string>("UserId");

                    b.Property<string>("Answer")
                        .HasMaxLength(4000);

                    b.Property<string>("UserName");

                    b.HasKey("PollId", "UserId");

                    b.ToTable("PollAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
