// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SkypeBot.Entities;
using System;

namespace SkypeBot.Migrations
{
    [DbContext(typeof(SkypeBotContext))]
    [Migration("20180218212259_Schema")]
    partial class Schema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("skype")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Apprefine.MattermostBots.SkypeBot.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChannelId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Apprefine.MattermostBots.SkypeBot.Entities.UserGroup", b =>
                {
                    b.Property<int>("GroupId");

                    b.Property<string>("UserId");

                    b.HasKey("GroupId", "UserId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("SkypeBot.Entities.UserInfo", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("SkypeSID");

                    b.HasKey("UserId", "SkypeSID");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("Apprefine.MattermostBots.SkypeBot.Entities.UserGroup", b =>
                {
                    b.HasOne("Apprefine.MattermostBots.SkypeBot.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
