// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SkypeBot.Entities;
using System;

namespace SkypeBot.Migrations
{
    [DbContext(typeof(SkypeBotContext))]
    [Migration("20180212184910_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("SkypeBot.Entities.UserInfo", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("SkypeSID");

                    b.HasKey("UserId", "SkypeSID");

                    b.ToTable("UserInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
